# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Japanese Translator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "ROGoogleTranslate"

  target 'Japanese TranslatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Japanese TranslatorUITests' do
    # Pods for testing
  end

end
